# Generated by Django 3.2.5 on 2021-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='is_correct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
